# Server Configuration
server.port=5050

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/tradewithai_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Arjun12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

# AI Configuration
# Options: gemini, ollama, groq, fallback
tradepilot.ai.provider=ollama
tradepilot.ai.gemini.key=
tradepilot.ai.ollama.url=http://localhost:11434
tradepilot.ai.ollama.model=llama3.2:latest
tradepilot.ai.groq.key=
tradepilot.ai.groq.model=llama-3.1-8b-instant

# Upstox Configuration
upstox.api.key=61728204-1bc4-472c-8d0a-195f6a35f078
upstox.api.secret=vgoyu0jw2z
upstox.redirect.uri=http://localhost:5050/api/upstox/callback
